export interface CountryData {
  text: string;
  value: string;
  coordinates: number[];
  openStreetmap?: string;
}

export const FALLBACK_COUNTRIES: CountryData[] = [
  { text: "🇦🇫 Afghanistan", value: "AF", coordinates: [33, 65] },
  { text: "🇦🇱 Albania", value: "AL", coordinates: [41, 20] },
  { text: "🇩🇿 Algeria", value: "DZ", coordinates: [28, 3] },
  { text: "🇦🇩 Andorra", value: "AD", coordinates: [42.5, 1.5] },
  { text: "🇦🇴 Angola", value: "AO", coordinates: [-12.5, 18.5] },
  { text: "🇦🇬 Antigua and Barbuda", value: "AG", coordinates: [17.05, -61.8] },
  { text: "🇦🇷 Argentina", value: "AR", coordinates: [-34, -64] },
  { text: "🇦🇲 Armenia", value: "AM", coordinates: [40, 45] },
  { text: "🇦🇺 Australia", value: "AU", coordinates: [-27, 133] },
  { text: "🇦🇹 Austria", value: "AT", coordinates: [47.33, 13.33] },
  { text: "🇦🇿 Azerbaijan", value: "AZ", coordinates: [40.5, 47.5] },
  { text: "🇧🇸 Bahamas", value: "BS", coordinates: [24.25, -76] },
  { text: "🇧🇭 Bahrain", value: "BH", coordinates: [26, 50.55] },
  { text: "🇧🇩 Bangladesh", value: "BD", coordinates: [24, 90] },
  { text: "🇧🇧 Barbados", value: "BB", coordinates: [13.16, -59.55] },
  { text: "🇧🇾 Belarus", value: "BY", coordinates: [53, 28] },
  { text: "🇧🇪 Belgium", value: "BE", coordinates: [50.83, 4] },
  { text: "🇧🇿 Belize", value: "BZ", coordinates: [17.25, -88.75] },
  { text: "🇧🇯 Benin", value: "BJ", coordinates: [9.5, 2.25] },
  { text: "🇧🇹 Bhutan", value: "BT", coordinates: [27.5, 90.5] },
  { text: "🇧🇴 Bolivia", value: "BO", coordinates: [17, -65] },
  { text: "🇧🇦 Bosnia and Herzegovina", value: "BA", coordinates: [44, 18] },
  { text: "🇧🇼 Botswana", value: "BW", coordinates: [-22, 24] },
  { text: "🇧🇷 Brazil", value: "BR", coordinates: [-10, -55] },
  { text: "🇧🇳 Brunei", value: "BN", coordinates: [4.5, 114.67] },
  { text: "🇧🇬 Bulgaria", value: "BG", coordinates: [43, 25] },
  { text: "🇧🇫 Burkina Faso", value: "BF", coordinates: [13, -2] },
  { text: "🇧🇮 Burundi", value: "BI", coordinates: [-3.5, 30] },
  { text: "🇨🇻 Cabo Verde", value: "CV", coordinates: [16, -24] },
  { text: "🇰🇭 Cambodia", value: "KH", coordinates: [13, 105] },
  { text: "🇨🇲 Cameroon", value: "CM", coordinates: [6, 12] },
  { text: "🇨🇦 Canada", value: "CA", coordinates: [60, -95] },
  { text: "🇨🇫 Central African Republic", value: "CF", coordinates: [7, 21] },
  { text: "🇹🇩 Chad", value: "TD", coordinates: [15, 19] },
  { text: "🇨🇱 Chile", value: "CL", coordinates: [-30, -71] },
  { text: "🇨🇳 China", value: "CN", coordinates: [35, 104] },
  { text: "🇨🇴 Colombia", value: "CO", coordinates: [4, -72] },
  { text: "🇰🇲 Comoros", value: "KM", coordinates: [-12.17, 44.25] },
  { text: "🇨🇬 Congo", value: "CG", coordinates: [-1, 15] },
  { text: "🇨🇩 Congo (Democratic Republic)", value: "CD", coordinates: [0, 25] },
  { text: "🇨🇷 Costa Rica", value: "CR", coordinates: [10, -84] },
  { text: "🇭🇷 Croatia", value: "HR", coordinates: [45.16, 15.5] },
  { text: "🇨🇺 Cuba", value: "CU", coordinates: [21.5, -80] },
  { text: "🇨🇾 Cyprus", value: "CY", coordinates: [35, 33] },
  { text: "🇨🇿 Czechia", value: "CZ", coordinates: [49.75, 15.5] },
  { text: "🇩🇰 Denmark", value: "DK", coordinates: [56, 10] },
  { text: "🇩🇯 Djibouti", value: "DJ", coordinates: [11.5, 43] },
  { text: "🇩🇲 Dominica", value: "DM", coordinates: [15.42, -61.33] },
  { text: "🇩🇴 Dominican Republic", value: "DO", coordinates: [19, -70.66] },
  { text: "🇪🇨 Ecuador", value: "EC", coordinates: [-2, -77.5] },
  { text: "🇪🇬 Egypt", value: "EG", coordinates: [27, 30] },
  { text: "🇸🇻 El Salvador", value: "SV", coordinates: [13.83, -88.92] },
  { text: "🇬🇶 Equatorial Guinea", value: "GQ", coordinates: [2, 10] },
  { text: "🇪🇷 Eritrea", value: "ER", coordinates: [15, 39] },
  { text: "🇪🇪 Estonia", value: "EE", coordinates: [59, 26] },
  { text: "🇸🇿 Eswatini", value: "SZ", coordinates: [-26.5, 31.5] },
  { text: "🇪🇹 Ethiopia", value: "ET", coordinates: [8, 38] },
  { text: "🇫🇯 Fiji", value: "FJ", coordinates: [-18, 175] },
  { text: "🇫🇮 Finland", value: "FI", coordinates: [64, 26] },
  { text: "🇫🇷 France", value: "FR", coordinates: [46, 2] },
  { text: "🇬🇦 Gabon", value: "GA", coordinates: [-1, 11.75] },
  { text: "🇬🇲 Gambia", value: "GM", coordinates: [13.47, -16.57] },
  { text: "🇬🇪 Georgia", value: "GE", coordinates: [42, 43.5] },
  { text: "🇩🇪 Germany", value: "DE", coordinates: [51, 9] },
  { text: "🇬🇭 Ghana", value: "GH", coordinates: [8, -2] },
  { text: "🇬🇷 Greece", value: "GR", coordinates: [39, 22] },
  { text: "🇬🇩 Grenada", value: "GD", coordinates: [12.11, -61.67] },
  { text: "🇬🇹 Guatemala", value: "GT", coordinates: [15.5, -90.25] },
  { text: "🇬🇳 Guinea", value: "GN", coordinates: [11, -10] },
  { text: "🇬🇼 Guinea-Bissau", value: "GW", coordinates: [12, -15] },
  { text: "🇬🇾 Guyana", value: "GY", coordinates: [5, -59] },
  { text: "🇭🇹 Haiti", value: "HT", coordinates: [19, -72.41] },
  { text: "🇭🇳 Honduras", value: "HN", coordinates: [15, -86.5] },
  { text: "🇭🇺 Hungary", value: "HU", coordinates: [47, 20] },
  { text: "🇮🇸 Iceland", value: "IS", coordinates: [65, -18] },
  { text: "🇮🇳 India", value: "IN", coordinates: [20, 77] },
  { text: "🇮🇩 Indonesia", value: "ID", coordinates: [-5, 120] },
  { text: "🇮🇷 Iran", value: "IR", coordinates: [32, 53] },
  { text: "🇮🇶 Iraq", value: "IQ", coordinates: [33, 44] },
  { text: "🇮🇪 Ireland", value: "IE", coordinates: [53, -8] },
  { text: "🇮🇱 Israel", value: "IL", coordinates: [31.5, 34.75] },
  { text: "🇮🇹 Italy", value: "IT", coordinates: [42.83, 12.83] },
  { text: "🇯🇲 Jamaica", value: "JM", coordinates: [18.25, -77.5] },
  { text: "🇯🇵 Japan", value: "JP", coordinates: [36, 138] },
  { text: "🇯🇴 Jordan", value: "JO", coordinates: [31, 36] },
  { text: "🇰🇿 Kazakhstan", value: "KZ", coordinates: [48, 68] },
  { text: "🇰🇪 Kenya", value: "KE", coordinates: [1, 38] },
  { text: "🇰🇮 Kiribati", value: "KI", coordinates: [1.42, 173] },
  { text: "🇰🇼 Kuwait", value: "KW", coordinates: [29.37, 47.97] },
  { text: "🇰🇬 Kyrgyzstan", value: "KG", coordinates: [41, 75] },
  { text: "🇱🇦 Laos", value: "LA", coordinates: [18, 105] },
  { text: "🇱🇻 Latvia", value: "LV", coordinates: [57, 25] },
  { text: "🇱🇧 Lebanon", value: "LB", coordinates: [33.83, 35.83] },
  { text: "🇱🇸 Lesotho", value: "LS", coordinates: [-29.5, 28.25] },
  { text: "🇱🇷 Liberia", value: "LR", coordinates: [6.5, -9.5] },
  { text: "🇱🇾 Libya", value: "LY", coordinates: [25, 17] },
  { text: "🇱🇮 Liechtenstein", value: "LI", coordinates: [47.16, 9.53] },
  { text: "🇱🇹 Lithuania", value: "LT", coordinates: [56, 24] },
  { text: "🇱🇺 Luxembourg", value: "LU", coordinates: [49.75, 6.16] },
  { text: "🇲🇬 Madagascar", value: "MG", coordinates: [-20, 47] },
  { text: "🇲🇼 Malawi", value: "MW", coordinates: [-13.5, 34] },
  { text: "🇲🇾 Malaysia", value: "MY", coordinates: [2.5, 112.5] },
  { text: "🇲🇻 Maldives", value: "MV", coordinates: [3.25, 73] },
  { text: "🇲🇱 Mali", value: "ML", coordinates: [17, -4] },
  { text: "🇲🇹 Malta", value: "MT", coordinates: [35.83, 14.58] },
  { text: "🇲🇭 Marshall Islands", value: "MH", coordinates: [9, 168] },
  { text: "🇲🇷 Mauritania", value: "MR", coordinates: [20, -12] },
  { text: "🇲🇺 Mauritius", value: "MU", coordinates: [-20.28, 57.55] },
  { text: "🇲🇽 Mexico", value: "MX", coordinates: [23, -102] },
  { text: "🇫🇲 Micronesia", value: "FM", coordinates: [6.92, 158.25] },
  { text: "🇲🇩 Moldova", value: "MD", coordinates: [47, 29] },
  { text: "🇲🇨 Monaco", value: "MC", coordinates: [43.73, 7.42] },
  { text: "🇲🇳 Mongolia", value: "MN", coordinates: [46, 105] },
  { text: "🇲🇪 Montenegro", value: "ME", coordinates: [42.5, 19.3] },
  { text: "🇲🇦 Morocco", value: "MA", coordinates: [32, -5] },
  { text: "🇲🇿 Mozambique", value: "MZ", coordinates: [-18.25, 35] },
  { text: "🇲🇲 Myanmar", value: "MM", coordinates: [22, 98] },
  { text: "🇳🇦 Namibia", value: "NA", coordinates: [-22, 17] },
  { text: "🇳🇷 Nauru", value: "NR", coordinates: [-0.53, 166.92] },
  { text: "🇳🇵 Nepal", value: "NP", coordinates: [28, 84] },
  { text: "🇳🇱 Netherlands", value: "NL", coordinates: [52.5, 5.75] },
  { text: "🇳🇿 New Zealand", value: "NZ", coordinates: [-41, 174] },
  { text: "🇳🇮 Nicaragua", value: "NI", coordinates: [13, -85] },
  { text: "🇳🇪 Niger", value: "NE", coordinates: [16, 8] },
  { text: "🇳🇬 Nigeria", value: "NG", coordinates: [10, 8] },
  { text: "🇰🇵 North Korea", value: "KP", coordinates: [40, 127] },
  { text: "🇲🇰 North Macedonia", value: "MK", coordinates: [41.83, 22] },
  { text: "🇳🇴 Norway", value: "NO", coordinates: [62, 10] },
  { text: "🇴🇲 Oman", value: "OM", coordinates: [21, 57] },
  { text: "🇵🇰 Pakistan", value: "PK", coordinates: [30, 70] },
  { text: "🇵🇼 Palau", value: "PW", coordinates: [7.5, 134.5] },
  { text: "🇵🇸 Palestine", value: "PS", coordinates: [32, 35.25] },
  { text: "🇵🇦 Panama", value: "PA", coordinates: [9, -80] },
  { text: "🇵🇬 Papua New Guinea", value: "PG", coordinates: [-6, 147] },
  { text: "🇵🇾 Paraguay", value: "PY", coordinates: [-23, -58] },
  { text: "🇵🇪 Peru", value: "PE", coordinates: [-10, -76] },
  { text: "🇵🇭 Philippines", value: "PH", coordinates: [13, 122] },
  { text: "🇵🇱 Poland", value: "PL", coordinates: [52, 20] },
  { text: "🇵🇹 Portugal", value: "PT", coordinates: [39.5, -8] },
  { text: "🇶🇦 Qatar", value: "QA", coordinates: [25.5, 51.25] },
  { text: "🇷🇴 Romania", value: "RO", coordinates: [46, 25] },
  { text: "🇷🇺 Russia", value: "RU", coordinates: [60, 100] },
  { text: "🇷🇼 Rwanda", value: "RW", coordinates: [-2, 30] },
  { text: "🇰🇳 Saint Kitts and Nevis", value: "KN", coordinates: [17.33, -62.75] },
  { text: "🇱🇨 Saint Lucia", value: "LC", coordinates: [13.88, -61.13] },
  { text: "🇻🇨 Saint Vincent and the Grenadines", value: "VC", coordinates: [13.25, -61.2] },
  { text: "🇼🇸 Samoa", value: "WS", coordinates: [-13.58, -172.33] },
  { text: "🇸🇲 San Marino", value: "SM", coordinates: [43.77, 12.42] },
  { text: "🇸🇹 Sao Tome and Principe", value: "ST", coordinates: [1, 7] },
  { text: "🇸🇦 Saudi Arabia", value: "SA", coordinates: [25, 45] },
  { text: "🇸🇳 Senegal", value: "SN", coordinates: [14, -14] },
  { text: "🇷🇸 Serbia", value: "RS", coordinates: [44, 21] },
  { text: "🇸🇨 Seychelles", value: "SC", coordinates: [-4.58, 55.66] },
  { text: "🇸🇱 Sierra Leone", value: "SL", coordinates: [8.5, -11.5] },
  { text: "🇸🇬 Singapore", value: "SG", coordinates: [1.36, 103.8] },
  { text: "🇸🇰 Slovakia", value: "SK", coordinates: [48.66, 19.5] },
  { text: "🇸🇮 Slovenia", value: "SI", coordinates: [46, 15] },
  { text: "🇸🇧 Solomon Islands", value: "SB", coordinates: [-8, 159] },
  { text: "🇸🇴 Somalia", value: "SO", coordinates: [10, 49] },
  { text: "🇿🇦 South Africa", value: "ZA", coordinates: [-29, 24] },
  { text: "🇰🇷 South Korea", value: "KR", coordinates: [37, 127.5] },
  { text: "🇸🇸 South Sudan", value: "SS", coordinates: [7, 30] },
  { text: "🇪🇸 Spain", value: "ES", coordinates: [40, -4] },
  { text: "🇱🇰 Sri Lanka", value: "LK", coordinates: [7, 81] },
  { text: "🇸🇩 Sudan", value: "SD", coordinates: [15, 30] },
  { text: "🇸🇷 Suriname", value: "SR", coordinates: [4, -56] },
  { text: "🇸🇪 Sweden", value: "SE", coordinates: [62, 15] },
  { text: "🇨🇭 Switzerland", value: "CH", coordinates: [47, 8] },
  { text: "🇸🇾 Syria", value: "SY", coordinates: [35, 38] },
  { text: "🇹🇼 Taiwan", value: "TW", coordinates: [23.5, 121] },
  { text: "🇹🇯 Tajikistan", value: "TJ", coordinates: [39, 71] },
  { text: "🇹🇿 Tanzania", value: "TZ", coordinates: [-6, 35] },
  { text: "🇹🇭 Thailand", value: "TH", coordinates: [15, 100] },
  { text: "🇹🇱 Timor-Leste", value: "TL", coordinates: [-8.83, 125.91] },
  { text: "🇹🇬 Togo", value: "TG", coordinates: [8, 1.16] },
  { text: "🇹🇴 Tonga", value: "TO", coordinates: [-20, -175] },
  { text: "🇹🇹 Trinidad and Tobago", value: "TT", coordinates: [10.5, -61.2] },
  { text: "🇹🇳 Tunisia", value: "TN", coordinates: [34, 9] },
  { text: "🇹🇷 Turkey", value: "TR", coordinates: [39, 35] },
  { text: "🇹🇲 Turkmenistan", value: "TM", coordinates: [40, 60] },
  { text: "🇹🇻 Tuvalu", value: "TV", coordinates: [-8, 178] },
  { text: "🇺🇬 Uganda", value: "UG", coordinates: [1, 32] },
  { text: "🇺🇦 Ukraine", value: "UA", coordinates: [49, 32] },
  { text: "🇦🇪 United Arab Emirates", value: "AE", coordinates: [24, 54] },
  { text: "🇬🇧 United Kingdom", value: "GB", coordinates: [54, -2] },
  { text: "🇺🇸 United States", value: "US", coordinates: [38, -97] },
  { text: "🇺🇾 Uruguay", value: "UY", coordinates: [-33, -56] },
  { text: "🇺🇿 Uzbekistan", value: "UZ", coordinates: [41, 64] },
  { text: "🇻🇺 Vanuatu", value: "VU", coordinates: [-16, 167] },
  { text: "🇻🇦 Vatican City", value: "VA", coordinates: [41.9, 12.45] },
  { text: "🇻🇪 Venezuela", value: "VE", coordinates: [8, -66] },
  { text: "🇻🇳 Vietnam", value: "VN", coordinates: [16, 108] },
  { text: "🇾🇪 Yemen", value: "YE", coordinates: [15, 48] },
  { text: "🇿🇲 Zambia", value: "ZM", coordinates: [-15, 30] },
  { text: "🇿🇼 Zimbabwe", value: "ZW", coordinates: [-20, 30] }
].sort((a, b) => a.text.localeCompare(b.text));